const cars = [{
  id: 1,
  owner: 1,
  email: 'user@example.com',
  createdOn: Date(),
  state: 'new',
  status: 'sold',
  price: 150000.00,
  manufacturer: 'Ford',
  model: '2009',
  bodyType: 'truck',
  imageUrl: 'url',
},
{
  id: 2,
  owner: 2,
  email: 'seyi@example.com',
  createdOn: Date(),
  state: 'used',
  status: 'available',
  price: 2000000.00,
  manufacturer: 'Ford',
  model: '2010',
  bodyType: 'van',
  imageUrl: 'url',
},
{
  id: 3,
  owner: 3,
  email: 'tobe@example.com',
  createdOn: Date(),
  state: 'new',
  status: 'available',
  price: 150000.00,
  manufacturer: 'Ford',
  model: '2009',
  bodyType: 'car',
  imageUrl: 'url',
},
{
  id: 4,
  owner: 4,
  email: 'glo@example.com',
  createdOn: Date(),
  state: 'used',
  status: 'available',
  price: 150000.00,
  manufacturer: 'Ford',
  model: '2009',
  bodyType: 'car',
  imageUrl: 'url',
},
];

export default cars;
